default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000
  username: video_sharing
  password: getwithit

development:
  <<: *default
  database: vs_development2

test:
  <<: *default
  pool: 4
  database: vs_test2



production:
  <<: *default
  pool: 5
  database: vs_production2

